### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by couto** [TheBITLINK/number-one-hundred#1]
It could probably be even faster if the `for` cycle is reversed: https://jsperf.com/get-100

![screen shot 2016-04-06 at 01 23 08](https://cloud.githubusercontent.com/assets/165314/14302194/448fb606-fb96-11e5-911b-e4cc59b1bdcc.png)

Imagine the speed gains :car:

P.S.: Results may vary...

**Comment by TheBITLINK** [comment]
wow... might implement it that way then...
![capture20160406005041742](https://cloud.githubusercontent.com/assets/3434300/14306515/af9c3014-fb91-11e5-8c5e-b6c911400917.png)
